{
 "title": "CoreRAD",
 "description": "Prometheus metrics dashboard for CoreRAD: https://github.com/mdlayher/corerad",
 "tags": [
  "corerad",
  "networking",
  "ipv6"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "corerad_build_info" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CoreRAD version",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "corerad_build_info{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Dates and times",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "corerad_build_timestamp_seconds{instance=\"$instance\"} * 1000",
     "legendFormat": "Build Time"
    },
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"} * 1000",
     "legendFormat": "Start Time"
    }
   ]
  },
  {
   "title": "Interface configuration",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "corerad_interface_advertising{instance=\"$instance\"} + 0"
    },
    {
     "expr": "corerad_interface_monitoring{instance=\"$instance\"} + 0"
    },
    {
     "expr": "corerad_interface_autoconfiguration{instance=\"$instance\"} + 0"
    },
    {
     "expr": "corerad_interface_forwarding{instance=\"$instance\"} + 0"
    }
   ]
  },
  { "title": "Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Default route lifetime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "corerad_monitor_default_route_expiration_timestamp_seconds{instance=\"$instance\"} - time()",
     "legendFormat": "{{interface}} : {{router}}"
    }
   ]
  },
  {
   "title": "Upstream prefix route lifetimes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "corerad_monitor_prefix_preferred_expiration_timestamp_seconds{instance=\"$instance\"} - time()",
     "legendFormat": "{{interface}}: {{prefix}} preferred via {{router}}"
    },
    {
     "expr": "corerad_monitor_prefix_valid_expiration_timestamp_seconds{instance=\"$instance\"} - time()",
     "legendFormat": "{{interface}}: {{prefix}} valid via {{router}}"
    }
   ]
  },
  {
   "title": "Monitor messages received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(corerad_monitor_messages_received_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{interface}}: {{host}}: {{message}}"
    }
   ]
  },
  { "title": "Advertiser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Router Advertisement prefix information",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(corerad_advertiser_prefix_preferred_seconds{instance=\"$instance\"} + on(instance, interface) group_left corerad_advertiser_last_multicast_time_seconds) - time()"
    },
    {
     "expr": "(corerad_advertiser_prefix_valid_seconds{instance=\"$instance\"} + on(instance, interface) group_left corerad_advertiser_last_multicast_time_seconds) - time()"
    },
    {
     "expr": "corerad_advertiser_prefix_autonomous{instance=\"$instance\"} + 0"
    }
   ]
  },
  {
   "title": "Advertiser messages received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(corerad_advertiser_messages_received_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{interface}}: {{message}}"
    }
   ]
  },
  {
   "title": "Inconsistent Router Advertisements received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(corerad_advertiser_inconsistencies_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{interface}}: {{field}}"
    }
   ]
  },
  {
   "title": "Router Advertisements sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(corerad_advertiser_router_advertisements_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{interface}}: {{type}}"
    }
   ]
  },
  {
   "title": "Advertiser errors per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(corerad_advertiser_errors_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{interface}}: {{error}}"
    }
   ]
  }
 ]
}